"""Add start_window_minutes to Exam

Revision ID: 04aef1cb101e
Revises: 
Create Date: 2026-08-17 15:07:19.583355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04aef1cb101e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('start_window_minutes', sa.Integer(), nullable=False))
    op.drop_column('exams', 'overview')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exams', 'start_window_minutes')
    # ### end Alembic commands ###
