"""Add login_count to ExamEnrollment

Revision ID: 22ea8b6b2035
Revises: 04aef1cb101e
Create Date: 2026-08-17 19:38:32.004352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ea8b6b2035'
down_revision: Union[str, Sequence[str], None] = '04aef1cb101e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_enrollments', sa.Column('login_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_enrollments', 'login_count')
    # ### end Alembic commands ###
