name: Sync RDS to Supabase

# Allows you to trigger this workflow manually from the Actions tab in GitHub
on:
  workflow_dispatch:

jobs:
  sync:
    name: Transfer Data (RDS -> Supabase)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4



      - name: Sync RDS Data back to Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          RDS_DB_URL: ${{ secrets.RDS_DB_URL }}
        run: |
          chmod +x .github/scripts/db_transfer_rds_to_supabase.sh
          ./.github/scripts/db_transfer_rds_to_supabase.sh
